name: Build and test parallel downloader
on:
  push:
    branches:
      - main

jobs:
  compile_and_test_parallel_downloader:
    runs-on: ubuntu-latest
    steps:
      - run: echo "the compile_and_test_parallel_downloader beign"
      
      - name: Set up Go
        uses: actions/setup-go@v2.1.4
        with: 
          go-version: 1.18
        id: go

      - name: Checkout
        uses: actions/checkout@v3

      - name: go mod
        run: |
          go mod tidy

      - name: Basic build
        run: |
          pwd
          ls -l
          go build cmd/main.go
          ls -l

      - name: Basic test
        run: |
          go test ./...

      - name: test cover
        run: |
          go test ./... -covermode=count -coverprofile=coverage.out
          go tool cover -html=coverage.out -o=coverage.html
          cat coverage.html
          go tool cover -func=coverage.out -o=coverage.func
          cat coverage.func

      - name: Finish
        run: echo "the compile_and_test_parallel_downloader finish"